version: '3.7'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - dpdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpw
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  phpfpm:
    build: ./.docker-compose
    image: phpfpm-7.4:local
    restart: always
    depends_on:
      - "mariadb"
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx
    depends_on:
      - "mariadb"
      - "phpfpm"
    volumes:
      - ./:/var/www/html
      - ./.docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  dpdb:
