<?php //Do not edit this file by hand, it will be overwritten by the configuration utility. 
$PROJDESIGN_CONFIG['show_task_descriptions'] = '0';
$PROJDESIGN_CONFIG['chars_task_descriptions'] = '400';
?>
